---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install lm-sensors
  apt:
    name: lm-sensors
    state: present

- name: Install git
  apt:
    name: git
    state: present

- name: Install pip3
  apt:
    name: python-pip3
    state: present




- name: Update all packages
  apt:
    name: "*"
    state: latest

- name: Remove unused dependencies
  apt:
    autoremove: yes

- name: Clean up unused packages
  apt:
    autoclean: yes

- name: Reboot the machine
  reboot: