---
all:
  children:
    # k3s:
    #   children:
    #     master:
    #       hosts:
    #         master.cadse.net:
    #           pi_serial: "39d70ef3"


    #      nodes:
    #        hosts:
    #          node1.cadse.net:
    #             pi_serial: 
    #           node2.cadse.net:
    #             pi_serial:
    #           node3.cadse.net:
    #             pi_serial: "a1f1148c"

    tftp:
      hosts:
        tftp.cadse.net:
          no_fan: yes