---
  raspi:
    hosts:
       master.cadse.net:
#      node[1:3].cadse.net:
#    vars:
#      ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q carter@cadsen-gate"'

    include_vars: 
     - group_vars/all.yml