---
all:
  children:
    k3s:
      children:
        master:
          hosts:
            master.cadse.net:


        nodes:
          hosts:
            node[1:3].cadse.net:

    tftp:
      hosts:
        tftp.cadse.net:
          no_fan: yes