---
- name: "Initial Config as user pi"
  hosts: raspi
  become: yes
  remote_user: "pi"

  tasks:
    - name: Perform basic user configuration.
      import_tasks: tasks/users.yml

  vars_files: 
    - vars/main.yml
    - vars/vault.yml

- name: "Main Config as user {{ cluster_user }}"
  hosts: raspi
  become: yes
  remote_user: "{{ cluster_user }}"

  vars_files: 
    - vars/main.yml
    - vars/vault.yml

  pre_tasks:
    - name: Set up apt cache proxy.
      template:
        src: templates/30proxy.j2
        dest: /etc/apt/apt.conf.d/30proxy

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

  tasks:
    - name: Import system tasks. 
      import_tasks: tasks/system.yml

    - name: Install basic software.
      import_tasks: tasks/software.yml
