---
- name: Initial Config as user pi.
  hosts: all
  become: yes
  gather_facts: no
  remote_user: "pi"

  pre_tasks:
    - name: Test if remote user pi can connect.
      local_action: shell ssh -o GlobalKnownHostsFile=/dev/null -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i {{ private_key_location }} pi@{{ inventory_hostname }} "echo success"
      register: pi_enabled
      ignore_errors: yes

    - include_role:
        name: init_user
      when: pi_enabled.stdout == "success"

- name: "Basic Config as user {{ cluster_user }}."
  hosts: all
  become: yes

  roles:
    - common

- name: "Set up RPiFanControl."
  hosts: all
  become: yes

  roles:
    - rpifancontrol

- name: "Set up TFTP."
  hosts: tftp
  become: yes

  roles:
    - tftp

- name: "k3s prerequesites."
  hosts: k3s
  become: yes

  roles:
    - k3s/requirements