---
- hosts: raspi
  become: yes
  
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600


  tasks:
    - name: Perform basic user configuration.
      import_tasks: tasks/users.yml

    - name: Import system tasks. 
      import_tasks: tasks/system.yml

    - name: Install basic software.
      import_tasks: tasks/software.yml
