---
- name: Initial Config as user pi.
  hosts: all
  become: yes
  gather_facts: no
  remote_user: "pi"

  pre_tasks:
    - name: Test if remote user pi can connect.
      local_action: shell ssh -o GlobalKnownHostsFile=/dev/null -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i {{ private_key_location }} pi@{{ inventory_hostname }} "echo success"
      register: pi_enabled
      ignore_errors: yes

    - include_role:
        name: init_user
      when: pi_enabled.stdout == "success"

  tasks:

  vars_files: 
    - vars/main.yml
    - vars/vault.yml

- name: "Basic Config as user {{ cluster_user }}."
  hosts: all
  become: yes
  remote_user: "{{ cluster_user }}"

  vars_files: 
    - vars/main.yml
    - vars/vault.yml

  roles:
    - common

- name: "Set up RPiFanControl"
  hosts: all
  become: yes
  remote_user: "{{ cluster_user }}"

  vars_files:
    - vars/main.yml
    - vars/vault.yml

  roles:
    - rpifancontrol

- name: "Set up TFTP"
  hosts: tftp
  become: yes
  remote_user: "{{ cluster_user }}"

  vars_files:
    - vars/main.yml
    - vars/vault.yml

  roles:
    - tftp