---

- name: Install lm-sensors
  apt:
    name: lm-sensors
    state: present

- name: Install git
  apt:
    name: git
    state: present

- name: Install pip3
  apt:
    name: python3-pip
    state: present

- name: Install Python Package rpi_hardware_pwm
  pip:
    name: rpi_hardware_pwm
    executable: pip3

- name: Update all packages
  apt:
    name: "*"
    state: latest
  notify: reboot

- name: Remove unused dependencies
  apt:
    autoremove: yes

- name: Clean up unused packages
  apt:
    autoclean: yes

- name: Flush Handlers
  meta: flush_handlers