---
- name: Set Python 3 as standard 
  shell: |
    rm /usr/bin/python
    ln -s /usr/bin/python3 /usr/bin/python

- name: Set hostname to {{ inventory_hostname }}
  hostname:
    name: "{{ inventory_hostname }}"

- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1{{'\t'}}{{ inventory_hostname }}"

- name: Disable HDMI port
  lineinfile:
    path: /etc/rc.local
    state: present
    regexp: "^/usr/bin/tvservice"
    line: "/usr/bin/tvservice -o"
    insertbefore: "^exit"

- name: Setting up /boot/config.txt
  lineinfile:
    path: /boot/config.txt
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: EOF
    state: present
  with_items: "{{ raspberry_pi_boot_config_options }}"
    
- name: Activating cgroup support
  lineinfile:
    path: /boot/cmdline.txt
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true

- name: "Create directory for system scripts of user {{ cluster_user }}"
  file:
    path: "/home/{{ cluster_user }}/.scripts/"
    state: directory
    owner: "{{ cluster_user }}"
    group: "{{ cluster_user }}"

- name: "Transfer temperature.py to user {{ cluster_user }}"
  template:
    src: templates/temperature.py.j2
    dest: "/home/{{ cluster_user }}/.scripts/temperature.py"
    owner: "{{ cluster_user }}"

  
- name: Reboot the machine
  reboot:  
