---

cluster_become_password: "{{ vault_cluster_become_password }}"  
ansible_become_password: "{{ vault_cluster_become_password }}"
ssh_key: "{{ vault_ssh_key }}"
pi_password: "{{ vault_pi_password }}"

include_vars: "vault.yml"