---

cluster_user_password: "{{ vault_cluster_become_password }}"  
ansible_become_password: "{{ vault_cluster_become_password }}"
ssh_key: "{{ vault_ssh_key }}"
pi_password: "{{ vault_pi_password }}"
apt_cache_ip: "10.101.100.11"
apt_cache_port: "3142"
fan_min_temperature: 30
fan_max_temperature: 60

include_vars: "vault.yml"