---

cluster_user_password: "{{ vault_cluster_become_password }}"  
ansible_become_password: "{{ vault_cluster_become_password }}"
ssh_key: "{{ vault_ssh_key }}"
pi_password: "{{ vault_pi_password }}"
cluster_user: "{{ vault_cluster_user }}"
private_key_location: "{{ vault_private_key_location }}"
apt_cache_ip: "10.101.100.11"
apt_cache_port: "3142"
fan_min_temperature: 30
fan_max_temperature: 60
pi_timezone: "Europe/Berlin"

raspberry_pi_boot_config_options:
  # Set GPU Memory to 16MB
  - regexp: "^#?gpu_mem"
    line: "gpu_mem=16" 
  # Disable Wifi module
  - regexp: "^#?dtoverlay=disable-wifi"
    line: "dtoverlay=disable-wifi"
  # Disable BT module
  - regexp: "^#?dtoverlay=disable-bt"
    line: "dtoverlay=disable-bt"

rpifancontrol_boot_config_options:  
  # Enable hardware PWM
  - regexp: "^#?dtoverlay=pwm-2chan"
    line: "dtoverlay=pwm-2chan,pin=12,func=4,pin2=13,func2=4"

