---
- name: Install tftp
  apt:
    name: tftpd-hpa

- name: Configure tftp
  lineinfile:
    regexp: '^TFTP_OPTIONS="--secure"' 
    path: /etc/default/tftpd-hpa 
    line: 'TFTP_OPTIONS="--secure --create"'
  notify: restart tftpd