---
- name: Flush iptables.
  iptables:
    flush: yes
  changed_when: false # iptables always returns changed, would destroy imdepotence

- name: Activate iptables.
  community.general.alternatives:
    path: /usr/sbin/iptables-legacy
    name: iptables

- name: Activate iptablesv6.
  community.general.alternatives:
    path: /usr/sbin/ip6tables-legacy
    name: ip6tables

- name: Activating cgroup support.
  lineinfile:
    path: /boot/cmdline.txt
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  notify: reboot