---
- name: Set up apt cache proxy.
  template:
    src: templates/30proxy.j2
    dest: /etc/apt/apt.conf.d/30proxy

- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install pip3
  apt:
    name: python3-pip
    state: present

- name: Update all packages
  apt:
    name: "*"
    state: latest
  notify: reboot

- name: Remove unused dependencies
  apt:
    autoremove: yes

- name: Clean up unused packages
  apt:
    autoclean: yes

- name: Flush Handlers
  meta: flush_handlers