---
- name: Install Python Package rpi_hardware_pwm
  pip:
    name: rpi_hardware_pwm
    executable: pip3

- name: Update /boot/config.txt
  lineinfile:
    path: /boot/config.txt
    regexp: "{{ fan_item.regexp }}"
    line: "{{ fan_item.line }}"
    insertafter: EOF
    state: present
  with_items: "{{ rpifancontrol_boot_config_options }}"
  notify: reboot
  loop_control:
    loop_var: fan_item

- name: Transfer RPiFanControl.py to /usr/local/bin/.
  copy:
    src: scripts/RPiFanControl/RPiFanControl.py
    dest: /usr/local/bin/RPiFanControl.py
  notify: update RPiFanControl

- name: Transfer RPiFanControl.service to /etc/systemd/system/.
  copy:
    src: scripts/RPiFanControl/RPiFanControl.service
    dest: /etc/systemd/system/RPiFanControl.service    
  notify: update RPiFanControl

